### PR TITLE
New "statusBar" to change StatusBarIOS color

### PR DESCRIPTION
**Pull request by JonasJonny**
If we have dark backgroundColor for our header we want to change StatusBarIOS color to white.
We can choose from lightContent (white) or default (black) color.
Without setting statusBar current setting is not changed.

### CODE REVIEW

**Comment by JonasJonny** [comment]
I think it will be nice to have this.
But we can set this inside constructor as well.

**Comment by JonasJonny** [comment]
Done.

**Comment by Kureev** [comment]
Perfect, thanks!

**Comment by JonasJonny** [comment]
Maybe add statusBar prop to readme "Component props".

**Comment by Kureev** [comment]
Would you like to make a PR? I'll merge it and bump version

**Pull request merged**
