### PR TITLE
Added Example

### PR DESCRIPTION
**Pull request by kocyigityunus**
version 0.3.0 was not working.
added example with a better approach. includes modal example.
better nagivation bar layout in any condition.
example to hide back button.

### CODE REVIEW

**Comment by Kureev** [comment]
@kocyigityunus What exactly isn't working in 0.3.0 in your op?

**Comment by kocyigityunus** [comment]
nav bar was never showing.

**Comment by Kureev** [comment]
Can you post only the usage code with styles applied to navbar?

**Comment by kocyigityunus** [comment]
sure. i will do it in 12 hours.

**Comment by Kureev** [comment]
Nice! I'll also put here a working code. Will wait for your code :+1:

**Comment by kocyigityunus** [comment]
is this good ? or too much code ? 

https://gist.github.com/kocyigityunus/fa9ae1ef06b5ca00f75f

**Comment by kocyigityunus** [comment]
can you try is it working? this was working on the this pull request version.
not 0.3.0 version.

**Comment by Kureev** [comment]
@kocyigityunus I confirm, that it's an issue. But it's enough if you'll fix navbar styles only. I removed
```css
position: absolute;
left: 0;
top: 0;
```
and pushed 0.3.1 to prod. Let me know if it works good for you.

**Comment by Kureev** [comment]
Closed until feedback

**Pull request closed without merging**
