### PR TITLE
Status bar style

### PR DESCRIPTION
**Pull request by Mokto**
Hi,

I think I did it :P

#79 

You can know add **statusBarStyle**={styles.statusBar} to change the background of statusbar.

**style** is for navbar and **backgroundStyle** is for both status and navbar.

Please let me know if something is wrong.

### CODE REVIEW

**Comment by Kureev** [comment]
Wow, that was fast! And looks awesome! Thanks a lot! :heart: :+1:

**Comment by Kureev** [comment]
Btw, can you also add notice about it to README?

**Comment by Mokto** [comment]
:smile: 

Sure, I didn't know when to do it ^^

Did you see I added 0.12.0-rc support ?

**Comment by Kureev** [comment]
Yep, I'm fine with it (but next time it's better to make a separated PR)

**Comment by Mokto** [comment]
Okey, I will do that next time ;)

PR coming soon for readme (even if my english is far from perfect, I'm a french guy :P).

**Comment by Kureev** [comment]
Awesome, thanks man!

**Comment by Taakn** [comment]
This does not work for me on Android (RN 0.19, Android 5.1.1). The actual status bar cannot be modified, the code adds a second status bar above the nav bar (so essentially this acts as additional top padding for the nav bar). 

Thanks

**Comment by kkgelu** [comment]
@Taakn  I have the same issue on Android (API 23, RN 0.21), it looks like this:
```
              <NavigationBar
                tintColor='red'
                style={{backgroundColor: 'blue'}]}
                />
```
screen shot 2016-02-29 at 23 47 57

**Comment by Kureev** [comment]
I'm afraid there's no workaround for now

**Pull request merged**
