### PR TITLE
Update readme (status bar)

### PR DESCRIPTION
**Pull request by Mokto**

### CODE REVIEW

**Comment by Kureev** [comment]
You know, I'm thinking now... We can customize only background color for status bar, right? Mb we need to be more explicit about it? I think "style" may by confusing for people in most of the cases.

**Comment by Mokto** [comment]
You are absolutely right !

If it was me, it would add a string attribute to define background color, instead of making it an object.

```javascript
<Navbar background='#fff' [statusBarBackground='red'] style={{}} />
```
=> *background* for both navbar and statusbar
=> *statusBarBackground* for custom statusbar background
=> style for custom style on navbar only

But it is a big change !

What do you think ?

**Comment by Mokto** [comment]
If it is too radical, i can only make an statusBarBackground='red'... Whatever you want ;)

**Comment by Kureev** [comment]
Yeah, good proposal, I agree on it

**Comment by Kureev** [comment]
I'll take care about it, don't worry :+1:

**Comment by Mokto** [comment]
Nice !

Good job man ;)

**Pull request merged**
